{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757756647647, "stop": 1757756647743}], "start": 1757756641756, "stop": 1757756647743}], "start": 1757756641756, "stop": 1757756647743}, {"name": "验证登录表单可见", "status": "passed", "start": 1757756647743, "stop": 1757756647769}, {"name": "输入登录凭据", "status": "passed", "start": 1757756647769, "stop": 1757756653479}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "1a09bec4-ace0-43d9-a787-ca33abdb6b82-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "57933684-920e-4ac9-8f82-b4ed5c84f388-attachment.html", "type": "text/html"}], "start": 1757756653479, "stop": 1757756656623}], "attachments": [{"name": "截图_test_valid_user_login", "source": "5224a60e-f668-40ab-84b5-15ddf4fd4dab-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "7d23d95b-67ee-4efa-8833-a78f4ff5161e-attachment.txt", "type": "text/plain"}], "start": 1757756641756, "stop": 1757756656626, "uuid": "6ad1e532-3a6d-4b91-b9d0-f5a6605ad6f1", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "用户认证功能"}, {"name": "story", "value": "用户登录"}, {"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "2436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}