{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757750334810, "stop": 1757750334875}], "start": 1757750329129, "stop": 1757750334875}], "start": 1757750329129, "stop": 1757750334875}, {"name": "验证登录表单可见", "status": "passed", "start": 1757750334875, "stop": 1757750334896}, {"name": "输入登录凭据", "status": "passed", "start": 1757750334896, "stop": 1757750339951}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "86006e80-c985-4e3e-a4d4-d623116dcb04-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "21974088-5949-469d-b5e2-7bc9309c43be-attachment.html", "type": "text/html"}], "start": 1757750339952, "stop": 1757750343114}], "attachments": [{"name": "截图_test_valid_user_login", "source": "4cc56e08-adfe-4741-92bd-ebf9e70daccc-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "ab8bd0e5-28be-487f-97ca-ff32bfabcc38-attachment.txt", "type": "text/plain"}], "start": 1757750329129, "stop": 1757750343115, "uuid": "6759625e-f50e-449a-b01f-4b6e32e7335c", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "feature", "value": "用户认证功能"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "用户登录"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "20396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}