{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757756021735, "stop": 1757756021797}], "start": 1757756016427, "stop": 1757756021797}], "start": 1757756016427, "stop": 1757756021797}, {"name": "验证登录表单可见", "status": "passed", "start": 1757756021797, "stop": 1757756021820}, {"name": "输入登录凭据", "status": "passed", "start": 1757756021820, "stop": 1757756026780}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "a4d73a8e-bc75-4388-a5b1-c8795a8a86b4-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "06929f88-21c2-4474-a476-212665b9d388-attachment.html", "type": "text/html"}], "start": 1757756026780, "stop": 1757756029950}], "attachments": [{"name": "截图_test_valid_user_login", "source": "ec751b02-d18e-4688-9212-49705f95305b-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "986ec577-2655-4c53-93f4-6e98b5a89df9-attachment.txt", "type": "text/plain"}], "start": 1757756016427, "stop": 1757756029951, "uuid": "9d6f05dd-ae9a-491a-9fec-ec97f5de4732", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "story", "value": "用户登录"}, {"name": "feature", "value": "用户认证功能"}, {"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "18852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}