{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757756672684, "stop": 1757756672746}], "start": 1757756667155, "stop": 1757756672746}], "start": 1757756667155, "stop": 1757756672746}, {"name": "验证登录表单可见", "status": "passed", "start": 1757756672746, "stop": 1757756672766}, {"name": "输入登录凭据", "status": "passed", "start": 1757756672766, "stop": 1757756674389}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "9f8d8fb9-2fcc-41d4-b411-ebc733a491de-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "8fba066a-b959-4f6d-832e-90af96dbbe6c-attachment.html", "type": "text/html"}], "start": 1757756674389, "stop": 1757756678057}], "attachments": [{"name": "截图_test_valid_user_login", "source": "a446bcbc-6453-447f-a93a-d717f446a86e-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "df00891d-e222-4b9b-8722-43977c0a8857-attachment.txt", "type": "text/plain"}], "start": 1757756667153, "stop": 1757756678057, "uuid": "2bdbeb82-6687-408a-9645-f6284ae1fec8", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "用户认证功能"}, {"name": "story", "value": "用户登录"}, {"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "2436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}