{"uuid": "c2f0836e-7b82-4c54-8476-255e3da12539", "children": ["582a06be-bb0b-4bf9-a0bd-7fa3999dcdc1"], "befores": [{"name": "browser_setup", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'os' referenced before assignment\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\conftest.py\", line 74, in browser_setup\n    driver = _setup_chrome_driver(headless, config)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\conftest.py\", line 115, in _setup_chrome_driver\n    \"download.default_directory\": os.path.abspath(\"downloads\"),\n"}, "start": 1757748796213, "stop": 1757748796213}], "start": 1757748796213, "stop": 1757748796255}