{"uuid": "26b16ecc-fab3-4129-a522-cc2ad712cf4f", "children": ["7f5b8386-9d2c-4cc1-89ec-ccf986a01acf"], "befores": [{"name": "browser_setup", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'os' referenced before assignment\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\.venv1\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\conftest.py\", line 74, in browser_setup\n    driver = _setup_chrome_driver(headless, config)\n  File \"D:\\LAB\\Selenium-Pytest-POM\\conftest.py\", line 115, in _setup_chrome_driver\n    \"download.default_directory\": os.path.abspath(\"downloads\"),\n"}, "start": 1757749132113, "stop": 1757749132113}], "start": 1757749132113, "stop": 1757749132140}