{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757756733367, "stop": 1757756733432}], "start": 1757756727955, "stop": 1757756733432}], "start": 1757756727955, "stop": 1757756733432}, {"name": "验证登录表单可见", "status": "passed", "start": 1757756733432, "stop": 1757756733452}, {"name": "输入登录凭据", "status": "passed", "start": 1757756733453, "stop": 1757756738588}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "b8fd1d5d-4dec-4e39-984d-f439048f08b6-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "508c43ec-f69c-45d8-adac-134cd916da15-attachment.html", "type": "text/html"}], "start": 1757756738589, "stop": 1757756741725}], "attachments": [{"name": "截图_test_valid_user_login", "source": "666239be-ebd1-4438-bbed-61a2ba627b24-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "b6158d24-80a0-4472-837c-57dc13d10ed1-attachment.txt", "type": "text/plain"}], "start": 1757756727952, "stop": 1757756741726, "uuid": "7468c4f7-e8e8-47ba-b851-371439b1d7cf", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "用户认证功能"}, {"name": "story", "value": "用户登录"}, {"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "2436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}