{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757753503694, "stop": 1757753503758}], "start": 1757753498305, "stop": 1757753503758}], "start": 1757753498305, "stop": 1757753503758}, {"name": "验证登录表单可见", "status": "passed", "start": 1757753503758, "stop": 1757753503781}, {"name": "输入登录凭据", "status": "passed", "start": 1757753503781, "stop": 1757753508534}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "58aa1b47-713c-4788-989f-a66268a3d8af-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "0374b626-7a92-41d2-91a6-285563398250-attachment.html", "type": "text/html"}], "start": 1757753508534, "stop": 1757753511663}], "attachments": [{"name": "截图_test_valid_user_login", "source": "c94eb3d6-5e89-486f-8e20-f85d99837dd3-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "c2445db2-1e48-4cca-9d14-b39bfa39b61f-attachment.txt", "type": "text/plain"}], "start": 1757753498304, "stop": 1757753511664, "uuid": "f40d5786-b815-487b-acae-a23cf760858a", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "story", "value": "用户登录"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "用户认证功能"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "20344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}