{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757750311583, "stop": 1757750311644}], "start": 1757750305896, "stop": 1757750311644}], "start": 1757750305896, "stop": 1757750311644}, {"name": "验证登录表单可见", "status": "passed", "start": 1757750311644, "stop": 1757750311678}, {"name": "输入登录凭据", "status": "passed", "start": 1757750311678, "stop": 1757750313237}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "c13dea55-4260-41cb-88e4-e5ea2f0e1eb5-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "21fee6f2-c635-44b9-bd98-19590d48cbe4-attachment.html", "type": "text/html"}], "start": 1757750313237, "stop": 1757750316410}], "attachments": [{"name": "截图_test_valid_user_login", "source": "eca046db-93da-4a92-a515-71da62e5daf1-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "1ebe17a9-c225-4b89-af0c-8273f9eed8d9-attachment.txt", "type": "text/plain"}], "start": 1757750305896, "stop": 1757750316411, "uuid": "1524432a-6af5-412e-ba83-8db6e19091bd", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "feature", "value": "用户认证功能"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "用户登录"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "20396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}