{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757753477533, "stop": 1757753477606}], "start": 1757753472491, "stop": 1757753477606}], "start": 1757753472490, "stop": 1757753477606}, {"name": "验证登录表单可见", "status": "passed", "start": 1757753477606, "stop": 1757753477627}, {"name": "输入登录凭据", "status": "passed", "start": 1757753477627, "stop": 1757753482855}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "2b6c0988-f9c3-4174-b90d-5ce8f15d53b9-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "74d9cfc1-58ed-4fc8-8839-0febfd6964a8-attachment.html", "type": "text/html"}], "start": 1757753482855, "stop": 1757753485998}], "attachments": [{"name": "截图_test_valid_user_login", "source": "eafa9e64-860b-4397-b278-b9bef1495a3e-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "99fd42f8-b508-4b48-b673-b2babe45043c-attachment.txt", "type": "text/plain"}], "start": 1757753472489, "stop": 1757753485999, "uuid": "96518601-bdf8-42d9-9087-1292f01f5932", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "story", "value": "用户登录"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "用户认证功能"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "20344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}